"""Update models

Revision ID: 3db41846c219
Revises: 792c356ca09c
Create Date: 2025-03-15 08:35:09.689198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db41846c219'
down_revision: Union[str, None] = '792c356ca09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('catalogs_category_id_fkey', 'catalogs', type_='foreignkey')
    op.drop_column('catalogs', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('catalogs_category_id_fkey', 'catalogs', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
