"""Update user-product relationships

Revision ID: e58e7369efae
Revises: e34b9a4fcb16
Create Date: 2025-03-14 19:53:18.650903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58e7369efae'
down_revision: Union[str, None] = 'e34b9a4fcb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'catalogs', 'categories', ['category_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'categories', 'catalogs', ['catalog_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'catalogs', type_='foreignkey')
    # ### end Alembic commands ###
